apiVersion: apps/v1
kind: Deployment
metadata:
  name: skin-cancer-prediction
spec:
  replicas: 5
  selector:
    matchLabels:
      app: skin-cancer-prediction
  template:
    metadata:
      labels:
        app: skin-cancer-prediction
    spec:
      containers:
      - name: skin-cancer-prediction
        image: gcr.io/deep-learning-421017/skin-cancer-prediction:v8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
