name : Continuous Integration/Deployment to Kubernetes on GCP using GitHub Actions
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.10.14
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.14
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Authenticate Docker to Google Container Registry
      run: gcloud auth configure-docker gcr.io
    
    - name: Get docker image build dynamic from commit message
      id: get_commit_message
      run: echo "::set-output name=version::$(git log -1 --pretty=%B)"

    # - name: Set up new version in deployment.yaml
    #   run: sed -i "s|image: gcr.io/deep-learning-421017/skin-cancer-prediction:v1|image: gcr.io/deep-learning-421017/skin-cancer-prediction:${{ steps.get_commit_message.outputs.version }}|g" kubernetes/deployment.yaml

    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/deep-learning-421017/skin-cancer-prediction:v9 .
        docker push gcr.io/deep-learning-421017/skin-cancer-prediction:v9
      
    - name: Deploy to Kubernetes
      run: |
        gcloud container clusters get-credentials skin-cancer-prediction-cluster --zone europe-west1-b --project deep-learning-421017
        kubectl apply -f kubernetes/deployment.yaml
    
    - name: Check deployment status
      run: kubectl rollout status deployment/skin-cancer-prediction
    



    